version: 2.1
jobs:
  build:
    macos:
      xcode: "11.1.0"

    steps:
      - checkout

      - run:
          name: "System Information"
          command: xcodebuild -version

      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.6.4" > ~/.ruby-version

      - run:
          name: "Update Brew"
          command: |
            brew update

      - run:
          name: "Build and Test (CocoaPods)"
          command: pod lib lint --verbose

      - run:
          name: "Generate and Upload Code Coverage"
          command: |
            slather
            bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml -X coveragepy -X gcov -X xcode
